### ISSUE TITLE
Too much memory needed?

### ISSUE THREAD

**Issue by xushichao2016** [ekazakos/temporal-binding-network#17]
While we trained on the EPIC KITCHENS-55, they need very large memory! 128G of memory is not enough.

**Comment by ekazakos** [comment]
That was not the case for me. 128G were enough when I was training the model. And particularly, it doesn't make sense that you get the memory issue only in EPIC-KITCHENS-55 because a) it is smaller than EPIC-KITCHENS-100, and b) despite the size of the datasets we load batches in both training and testing. 

Any chance that you used a value for the --num_segments input argument larger than 3? Because this increases the memory requirements as more copies of the network should be in memory, one for each segment.
